import React, { Component } from 'react';
import { 
    ContentContainer, 
    ContentHeader, 
    Paragraph 
} from '../assets/styles'

class Home extends Component {
  render() {
    return (
      <ContentContainer>
      <ContentHeader>Content</ContentHeader>
          <Paragraph>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nisi leo, venenatis mollis dignissim dignissim, auctor a lectus. Etiam mattis, tortor sed feugiat lacinia, magna ex euismod nisl, id semper urna augue ultrices nisl. Vestibulum aliquam enim metus, quis tristique libero auctor quis. In pretium mauris non tincidunt tincidunt. Phasellus ac ipsum pharetra quam ornare suscipit vitae et leo. Maecenas at tellus et risus pharetra vestibulum. Mauris lobortis id eros sed sodales. Fusce tincidunt ac ante eu volutpat. Nunc eu nisi eget ex convallis congue. Morbi in cursus justo. Donec diam mauris, finibus cursus commodo eget, fermentum in orci. Maecenas a ipsum a turpis dictum euismod et in risus. Sed velit urna, vestibulum et risus vitae, scelerisque ultrices est. Aliquam sollicitudin justo sit amet magna convallis, et faucibus mauris sodales. Sed sed ex ac justo maximus tempus.</Paragraph>
          <Paragraph>Donec imperdiet tincidunt erat, vel pulvinar turpis varius vel. Aliquam venenatis ligula neque, eu hendrerit diam fringilla et. Morbi a eros quis lectus placerat tincidunt eu at felis. Maecenas tristique aliquam sem, condimentum pharetra lorem molestie sed. Maecenas in lacus consectetur, pellentesque neque sed, ullamcorper ante. Curabitur magna metus, euismod quis justo nec, sollicitudin scelerisque ligula. Morbi erat ex, facilisis id sodales quis, interdum eget elit. Nullam tincidunt vitae est ac auctor. Phasellus sed tortor sed metus egestas volutpat. Morbi rutrum massa dapibus arcu hendrerit pharetra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec luctus metus vitae facilisis ullamcorper. Integer sagittis tempor purus. Etiam auctor nulla sit amet pulvinar scelerisque. Phasellus id tellus a massa semper sollicitudin eu ut arcu. Quisque ornare urna eget massa tristique, feugiat maximus mi sodales.</Paragraph>
          <Paragraph>Praesent sed lacinia mauris, ut lobortis lacus. Vivamus at mauris id ante auctor auctor in ultrices enim. Nunc mollis purus nisi, non elementum velit tempor a. Integer auctor massa a justo dapibus, ut euismod mi molestie. Integer eget eleifend dolor. Aliquam erat volutpat. Curabitur finibus nulla aliquet, tincidunt nulla id, viverra tellus. Etiam euismod mauris id magna tristique aliquam. Praesent efficitur est eget eros commodo, non ornare turpis tincidunt. Vivamus consectetur tortor et magna iaculis pharetra. Proin lectus urna, posuere in erat eget, aliquet feugiat arcu.</Paragraph>
          <Paragraph>Nunc lobortis maximus arcu quis consectetur. Mauris rhoncus sollicitudin dui eget luctus. Vivamus ultricies ligula nec tempus bibendum. Nunc placerat consectetur magna, non dapibus ante lacinia vitae. Etiam urna turpis, bibendum quis vestibulum id, dictum non tellus. Nam quis interdum risus. Nunc nec elit consequat, sodales urna eu, blandit elit. In commodo sodales nisi. Donec accumsan libero non purus aliquet, in sagittis nunc commodo.</Paragraph>
          <Paragraph>Praesent lacinia, ligula a blandit venenatis, lorem mauris venenatis velit, at malesuada massa nisi a nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum blandit interdum enim, vitae aliquet tellus egestas imperdiet. Nam eu auctor turpis. Suspendisse ultrices bibendum fermentum. Quisque ut bibendum urna. Etiam ultricies vehicula lorem, eget rutrum lectus. Etiam blandit varius lectus, vel maximus velit ultrices id. Donec quis ullamcorper est. Nunc tempus dapibus ex nec varius.</Paragraph>
          <Paragraph>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nisi leo, venenatis mollis dignissim dignissim, auctor a lectus. Etiam mattis, tortor sed feugiat lacinia, magna ex euismod nisl, id semper urna augue ultrices nisl. Vestibulum aliquam enim metus, quis tristique libero auctor quis. In pretium mauris non tincidunt tincidunt. Phasellus ac ipsum pharetra quam ornare suscipit vitae et leo. Maecenas at tellus et risus pharetra vestibulum. Mauris lobortis id eros sed sodales. Fusce tincidunt ac ante eu volutpat. Nunc eu nisi eget ex convallis congue. Morbi in cursus justo. Donec diam mauris, finibus cursus commodo eget, fermentum in orci. Maecenas a ipsum a turpis dictum euismod et in risus. Sed velit urna, vestibulum et risus vitae, scelerisque ultrices est. Aliquam sollicitudin justo sit amet magna convallis, et faucibus mauris sodales. Sed sed ex ac justo maximus tempus.</Paragraph>
          <Paragraph>Donec imperdiet tincidunt erat, vel pulvinar turpis varius vel. Aliquam venenatis ligula neque, eu hendrerit diam fringilla et. Morbi a eros quis lectus placerat tincidunt eu at felis. Maecenas tristique aliquam sem, condimentum pharetra lorem molestie sed. Maecenas in lacus consectetur, pellentesque neque sed, ullamcorper ante. Curabitur magna metus, euismod quis justo nec, sollicitudin scelerisque ligula. Morbi erat ex, facilisis id sodales quis, interdum eget elit. Nullam tincidunt vitae est ac auctor. Phasellus sed tortor sed metus egestas volutpat. Morbi rutrum massa dapibus arcu hendrerit pharetra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec luctus metus vitae facilisis ullamcorper. Integer sagittis tempor purus. Etiam auctor nulla sit amet pulvinar scelerisque. Phasellus id tellus a massa semper sollicitudin eu ut arcu. Quisque ornare urna eget massa tristique, feugiat maximus mi sodales.</Paragraph>
          <Paragraph>Praesent sed lacinia mauris, ut lobortis lacus. Vivamus at mauris id ante auctor auctor in ultrices enim. Nunc mollis purus nisi, non elementum velit tempor a. Integer auctor massa a justo dapibus, ut euismod mi molestie. Integer eget eleifend dolor. Aliquam erat volutpat. Curabitur finibus nulla aliquet, tincidunt nulla id, viverra tellus. Etiam euismod mauris id magna tristique aliquam. Praesent efficitur est eget eros commodo, non ornare turpis tincidunt. Vivamus consectetur tortor et magna iaculis pharetra. Proin lectus urna, posuere in erat eget, aliquet feugiat arcu.</Paragraph>
          <Paragraph>Nunc lobortis maximus arcu quis consectetur. Mauris rhoncus sollicitudin dui eget luctus. Vivamus ultricies ligula nec tempus bibendum. Nunc placerat consectetur magna, non dapibus ante lacinia vitae. Etiam urna turpis, bibendum quis vestibulum id, dictum non tellus. Nam quis interdum risus. Nunc nec elit consequat, sodales urna eu, blandit elit. In commodo sodales nisi. Donec accumsan libero non purus aliquet, in sagittis nunc commodo.</Paragraph>
          <Paragraph>Praesent lacinia, ligula a blandit venenatis, lorem mauris venenatis velit, at malesuada massa nisi a nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum blandit interdum enim, vitae aliquet tellus egestas imperdiet. Nam eu auctor turpis. Suspendisse ultrices bibendum fermentum. Quisque ut bibendum urna. Etiam ultricies vehicula lorem, eget rutrum lectus. Etiam blandit varius lectus, vel maximus velit ultrices id. Donec quis ullamcorper est. Nunc tempus dapibus ex nec varius.</Paragraph>
          <Paragraph>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nisi leo, venenatis mollis dignissim dignissim, auctor a lectus. Etiam mattis, tortor sed feugiat lacinia, magna ex euismod nisl, id semper urna augue ultrices nisl. Vestibulum aliquam enim metus, quis tristique libero auctor quis. In pretium mauris non tincidunt tincidunt. Phasellus ac ipsum pharetra quam ornare suscipit vitae et leo. Maecenas at tellus et risus pharetra vestibulum. Mauris lobortis id eros sed sodales. Fusce tincidunt ac ante eu volutpat. Nunc eu nisi eget ex convallis congue. Morbi in cursus justo. Donec diam mauris, finibus cursus commodo eget, fermentum in orci. Maecenas a ipsum a turpis dictum euismod et in risus. Sed velit urna, vestibulum et risus vitae, scelerisque ultrices est. Aliquam sollicitudin justo sit amet magna convallis, et faucibus mauris sodales. Sed sed ex ac justo maximus tempus.</Paragraph>
          <Paragraph>Donec imperdiet tincidunt erat, vel pulvinar turpis varius vel. Aliquam venenatis ligula neque, eu hendrerit diam fringilla et. Morbi a eros quis lectus placerat tincidunt eu at felis. Maecenas tristique aliquam sem, condimentum pharetra lorem molestie sed. Maecenas in lacus consectetur, pellentesque neque sed, ullamcorper ante. Curabitur magna metus, euismod quis justo nec, sollicitudin scelerisque ligula. Morbi erat ex, facilisis id sodales quis, interdum eget elit. Nullam tincidunt vitae est ac auctor. Phasellus sed tortor sed metus egestas volutpat. Morbi rutrum massa dapibus arcu hendrerit pharetra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec luctus metus vitae facilisis ullamcorper. Integer sagittis tempor purus. Etiam auctor nulla sit amet pulvinar scelerisque. Phasellus id tellus a massa semper sollicitudin eu ut arcu. Quisque ornare urna eget massa tristique, feugiat maximus mi sodales.</Paragraph>
          <Paragraph>Praesent sed lacinia mauris, ut lobortis lacus. Vivamus at mauris id ante auctor auctor in ultrices enim. Nunc mollis purus nisi, non elementum velit tempor a. Integer auctor massa a justo dapibus, ut euismod mi molestie. Integer eget eleifend dolor. Aliquam erat volutpat. Curabitur finibus nulla aliquet, tincidunt nulla id, viverra tellus. Etiam euismod mauris id magna tristique aliquam. Praesent efficitur est eget eros commodo, non ornare turpis tincidunt. Vivamus consectetur tortor et magna iaculis pharetra. Proin lectus urna, posuere in erat eget, aliquet feugiat arcu.</Paragraph>
          <Paragraph>Nunc lobortis maximus arcu quis consectetur. Mauris rhoncus sollicitudin dui eget luctus. Vivamus ultricies ligula nec tempus bibendum. Nunc placerat consectetur magna, non dapibus ante lacinia vitae. Etiam urna turpis, bibendum quis vestibulum id, dictum non tellus. Nam quis interdum risus. Nunc nec elit consequat, sodales urna eu, blandit elit. In commodo sodales nisi. Donec accumsan libero non purus aliquet, in sagittis nunc commodo.</Paragraph>
          <Paragraph>Praesent lacinia, ligula a blandit venenatis, lorem mauris venenatis velit, at malesuada massa nisi a nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum blandit interdum enim, vitae aliquet tellus egestas imperdiet. Nam eu auctor turpis. Suspendisse ultrices bibendum fermentum. Quisque ut bibendum urna. Etiam ultricies vehicula lorem, eget rutrum lectus. Etiam blandit varius lectus, vel maximus velit ultrices id. Donec quis ullamcorper est. Nunc tempus dapibus ex nec varius.</Paragraph>

      </ContentContainer>
    );
  }
}

export default Home;